datasets:
  textcaps_caption:
    data_type: images
    
    build_info:
      image_path: /mnt/fast/nobackup/scratch4weeks/aj00869/textcaps/train_images/
      ann_path: /mnt/fast/nobackup/scratch4weeks/aj00869/textcaps/TextCaps_0.1_train.json


